/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ffmpeg_FFmpegUtil */

#ifndef _Included_com_example_ffmpeg_FFmpegUtil
#define _Included_com_example_ffmpeg_FFmpegUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ffmpeg_FFmpegUtil
 * Method:    test
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ffmpeg_FFmpegUtil_test
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_ffmpeg_FFmpegUtil
 * Method:    play
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_example_ffmpeg_FFmpegUtil_play
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
