/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eastcom_harup_utils_Player */

#ifndef _Included_com_eastcom_harup_utils_Player
#define _Included_com_eastcom_harup_utils_Player
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eastcom_harup_utils_Player
 * Method:    play
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_eastcom_harup_utils_Player_play
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
