/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eastcom_harup_utils_PosixUtil */

#ifndef _Included_com_eastcom_harup_utils_PosixUtil
#define _Included_com_eastcom_harup_utils_PosixUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eastcom_harup_utils_PosixUtil
 * Method:    runOtherThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_eastcom_harup_utils_PosixUtil_runOtherThread
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
