/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../../../../../../../android_sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/jni.h"

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eastcom_harup_utils_SoundEffectUtil
 * Method:    soundFix
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_eastcom_harup_utils_SoundEffectUtil_soundFix(JNIEnv *, jclass , jstring , jint );

#ifdef __cplusplus
}
#endif
